name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'git@github.com:shecodesvietnam/fe-mentorship.git'
          source_branch: 'dev'
          destination_repo: 'git@github.com:npthao1312/shecodes-mentorship.git'
          destination_branch: 'dev'
          destination_ssh_private_key: ${{ secrets.SSH_DEPLOY_KEY }}
